# Uncomment the next line to define a global platform for your project
 platform :ios, ‘9.0’


target 'Wasabi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wasabi
    pod 'RxSwift'
    pod 'RxCocoa'

  target 'WasabiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WasabiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
